domain_path: C:\PROJECTS_FPGA\Home_tasks\HT1\htL12_dma\vitis\DMA_MB\platform\export\platform\sw\standalone_microblaze_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
