domain_path: C:\PROJECTS_FPGA\Home_tasks\HT1\ht10_running_led\vitis\LED_AXI_GPIO_Zynq\platform_2\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
